/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 atomic.gltf --transform
Files: atomic.gltf [996.01KB] > atomic-transformed.glb [205.13KB] (79%)
Author: DavidFer (https://sketchfab.com/DavidFer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/reactor-nuclear-a72f3aa6e73d4b2ba663b225ea9b7202
Title: Reactor Nuclear
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'

export default function Model(props) {
    const {nodes, materials} = useGLTF('/atomic-transformed.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.pCylinder1_anisotropic19_0.geometry} material={materials.PaletteMaterial001}
                  position={[0, 0.896, 0]} scale={[0.854, 0.913, 0.854]}/>
            <mesh geometry={nodes.pCylinder6_lambert1_0.geometry} material={materials.PaletteMaterial002}
                  position={[0, 50.14, 0]} scale={[0.411, 1.486, 0.411]}/>
            <mesh geometry={nodes.pCylinder42_anisotropic20_0.geometry} material={materials.anisotropic20}
                  position={[-14.508, 21.823, -4.714]} rotation={[-1.755, -0.513, 1.208]} scale={0.798}/>
            <mesh geometry={nodes.pTorus1_blinn10_0.geometry} material={materials.PaletteMaterial003}
                  position={[0, 13.273, 0]} scale={[0.873, 1, 0.873]}/>
            <instancedMesh args={[nodes.pPlane7_blinn10_0.geometry, materials.PaletteMaterial003, 5]}
                           instanceMatrix={nodes.pPlane7_blinn10_0.instanceMatrix}/>
            <instancedMesh args={[nodes.pCylinder40_phongE9_0.geometry, materials.phongE9, 5]}
                           instanceMatrix={nodes.pCylinder40_phongE9_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface33_anisotropic10_0.geometry, materials.anisotropic10, 5]}
                           instanceMatrix={nodes.polySurface33_anisotropic10_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface38_anisotropic11_0.geometry, materials.anisotropic11, 5]}
                           instanceMatrix={nodes.polySurface38_anisotropic11_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface41_anisotropic13_0.geometry, materials.anisotropic13, 5]}
                           instanceMatrix={nodes.polySurface41_anisotropic13_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface45_anisotropic15_0.geometry, materials.anisotropic15, 5]}
                           instanceMatrix={nodes.polySurface45_anisotropic15_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface51_lambert1_0.geometry, materials.PaletteMaterial002, 5]}
                           instanceMatrix={nodes.polySurface51_lambert1_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface52_lambert1_0.geometry, materials.PaletteMaterial002, 5]}
                           instanceMatrix={nodes.polySurface52_lambert1_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface54_lambert1_0.geometry, materials.PaletteMaterial002, 5]}
                           instanceMatrix={nodes.polySurface54_lambert1_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface55_lambert1_0.geometry, materials.PaletteMaterial002, 5]}
                           instanceMatrix={nodes.polySurface55_lambert1_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface57_lambert1_0.geometry, materials.PaletteMaterial002, 5]}
                           instanceMatrix={nodes.polySurface57_lambert1_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface58_phong6_0.geometry, materials.PaletteMaterial004, 5]}
                           instanceMatrix={nodes.polySurface58_phong6_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface58_anisotropic2_0.geometry, materials.PaletteMaterial001, 5]}
                           instanceMatrix={nodes.polySurface58_anisotropic2_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface59_lambert1_0.geometry, materials.PaletteMaterial002, 5]}
                           instanceMatrix={nodes.polySurface59_lambert1_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface60_lambert1_0.geometry, materials.PaletteMaterial002, 5]}
                           instanceMatrix={nodes.polySurface60_lambert1_0.instanceMatrix}/>
            <instancedMesh args={[nodes.polySurface85_lambert7_0.geometry, materials.lambert7, 5]}
                           instanceMatrix={nodes.polySurface85_lambert7_0.instanceMatrix}/>
        </group>
    )
}

useGLTF.preload('/atomic-transformed.glb')
