/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 reactorLogo.gltf --transform
Files: reactorLogo.gltf [21.76MB] > reactorLogo-transformed.glb [2.76MB] (87%)
Author: Atmo (https://sketchfab.com/atmo_gd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arc-reactor-tony-stark-high-poly-7c57e1f6b3034194a1e3c8abb3a49df2
Title: Arc Reactor - Tony Stark - HIGH POLY
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'

export default function Model(props) {
    const {nodes, materials} = useGLTF('/reactorLogo-transformed.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Bottom_HP_Arc_0.geometry}
                  material={materials.material}
                  rotation={[0, 0.115, 0]}
            />
            <mesh geometry={nodes.BottomLight_HP_BottomLight_0.geometry}
                  material={materials.BottomLight}
                  rotation={[0, 0.115, 0]}
            />
        </group>
    )
}

useGLTF.preload('/reactorLogo-transformed.glb')
