/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 telegramLogo.gltf --transform
Files: telegramLogo.gltf [30.5KB] > telegramLogo-transformed.glb [35.42KB] (-16%)
Author: AlbertVictory (https://sketchfab.com/albert_victory)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/telegram-3d-icon-80421c5d474f4a3c8145ba4b9aaa7d2d
Title: Telegram 3D-icon
*/

import React from 'react';
import {useGLTF} from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/telegramLogo-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry}
        material={materials.material}
        position={[0, -0.02, -0.04]}
        rotation={[-2.884, 0, -Math.PI / 2]}
        scale={[1, 0.092, 1]}
      />
      <mesh geometry={nodes.Object_6.geometry}
        material={materials['Material.002']}
        position={[0.08, -0.054, 0.031]}
        rotation={[0, 0, -Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload('/telegramLogo-transformed.glb');
